"""add research_notes table

Revision ID: 7f805ed657bb
Revises: a6551666af3e
Create Date: 2026-07-11 21:59:03.374836

"""
from alembic import op
import sqlalchemy as sa


revision = '7f805ed657bb'
down_revision = 'a6551666af3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('interest_score', sa.Numeric(), nullable=True),
    sa.Column('scored_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_notes')
    # ### end Alembic commands ###
