"""add style_profile table

Revision ID: c3a9f1d8e2b4
Revises: 7f805ed657bb
Create Date: 2026-07-12 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


revision = 'c3a9f1d8e2b4'
down_revision = '7f805ed657bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tone_notes', sa.Text(), nullable=True),
    sa.Column('opening_patterns', sa.JSON(), nullable=True),
    sa.Column('closing_patterns', sa.JSON(), nullable=True),
    sa.Column('avg_length_seconds', sa.Numeric(), nullable=True),
    sa.Column('vocabulary_notes', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_profile')
    # ### end Alembic commands ###
